workflows:
  ios-workflow:
    name: SwiftDeal iOS Build
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic
    environment:
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.swiftdeal.app
    scripts:
      - name: Install Dependencies
        script: |
          cd "SwiftDeal IOS/src"
          pod install
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.swiftdeal.app" --type IOS_APP_STORE --create
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build the iOS App
        script: |
          cd "SwiftDeal IOS/src"
          xcode-project build-ipa --workspace "SwiftDeal IOS/src/SwiftDeal.xcworkspace" --scheme "SwiftDeal"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
